[Variables]
; --------------- Colors
DefaultColor0=255,216,60,255
Color=255,216,60
Color1=#Color#,200
ColorBlack=0,0,0,200
colorborder=255,255,255,20
changedcolorvariable=Change me
DefaultColor=255,216,60,255
last=
lastoriginal=0,0,0
lastnew=0,0,0

; ---------------- Positions and color mixing
pointery=0
apointery=204
redsetter=255
bluesetter=0
greensetter=0
tint=#redsetter#,#greensetter#,#bluesetter#
trueredsetter=255
truegreensetter=5
truebluesetter=5
alpha=51
crossx=251
crossy=0

