[Rainmeter]
Update=1000
DynamicWindowSize=1

[Metadata]
Author=Edhel, http://squirrel-slayer.deviantart.com
Information=Utility for changing color defined in the variables.inc
License=Creative Commons BY-NC-SA 3.0
Version=1

[Variables]
@Include=#@#variables.inc
@Include2=#@#variables-color.inc
@Include3=#SKINSPATH#TECH-B\SETTINGS\variables.inc

;-----------------------------------------------------------------------------------
;					Measures
;-----------------------------------------------------------------------------------

[Measureredsetter]
Measure=Calc
Formula=#redsetter#
UpdateDivider=-1

[Measuregreensetter]
Measure=Calc
Formula=#greensetter#
UpdateDivider=-1

[Measurebluesetter]
Measure=Calc
Formula=#bluesetter#
UpdateDivider=-1


[MeasureTrueredsetter]
Measure=Calc
Formula=#trueredsetter#
UpdateDivider=-1
OnUpdateAction=[!WriteKeyValue Variables trueredsetter [MeasureTrueredsetter] "#@#variables-color.inc"]

[MeasureTruegreensetter]
Measure=Calc
Formula=#truegreensetter#
UpdateDivider=-1
OnUpdateAction=[!WriteKeyValue Variables truegreensetter [MeasureTruegreensetter] "#@#variables-color.inc"]

[MeasureTruebluesetter]
Measure=Calc
Formula=#truebluesetter#
UpdateDivider=-1
OnUpdateAction=[!WriteKeyValue Variables truebluesetter [MeasureTruebluesetter] "#@#variables-color.inc"]

[InputColor]
Measure=Plugin
Plugin=InputText
SolidColor=#Color1#
FontColor=#ColorBlack#
StringStyle=Bold
StringAlign=Center
FontFace=Arial
FontSize=10
X=([ChangedVariable:X])
Y=([ChangedVariable:Y])
W=200
H=16
DefaultValue="#changedcolorvariable#"
FocusDismiss=1
DynamicVariables=1
Antialias=1
Command1=[!WriteKeyValue Variables changedcolorvariable "$UserInput$" "#@#variables-color.inc"]
Command2=[!WriteKeyValue Variables defaultcolor "#[InputColor]#" "#@#variables-color.inc"]
Command3=!Refresh

;-----------------------------------------------------------------------------------
;					Styles
;-----------------------------------------------------------------------------------

[Text]
FontSize=10
FontColor=#Color1#
AntiAlias=1
DynamicVariables=1

;-----------------------------------------------------------------------------------
;					Meters
;-----------------------------------------------------------------------------------

[BG]
Meter=Image
SolidColor=#ColorBlack#
X=0
Y=0
W=400
H=540

[Switch]
Meter=String
MeterStyle=Text
FontSize=8
StringAlign=Right
StringStyle=Bold
X=([BG:W])
Y=2
Text="RGBA variant here"
LeftMouseUpAction=[!ToggleConfig "#ROOTCONFIG#" "ColorSetter.ini"][!ToggleConfig "#ROOTCONFIG#" "ColorSetter-Alpha.ini"]

[Label]
Meter=String
MeterStyle=Text
FontSize=12
StringAlign=Center
StringStyle=Bold
X=([BG:W]/2)
Y=10
Text="Color setter RGB"


[VariableLabel]
Meter=String
MeterStyle=Text
StringAlign=Center
X=([BG:W]/2)
Y=5R
ClipString=2
ClipstringW=([BG:W]-20)
H=
Text=Set the name of variable you want change and press ENTER

[ChangedVariable]
Meter=String
MeterStyle=Text
StringAlign=Center
StringStyle=Bold
X=([BG:W]/2)
Y=55
W=200
H=16
Text=#changedcolorvariable#
SolidColor=255,255,255,100
LeftMouseUpAction=!CommandMeasure "InputColor" "ExecuteBatch 1-3"

[ChoseColor2]
Meter=String
MeterStyle=Text
StringAlign=Center
X=([BG:W]/2)
Y=5R
ClipString=2
CLipstringW=([BG:W]-20)
H=
Text="(First chose the tint on the left, then the shade in the box)"

;-------------- Tint
[TintBG]
Meter=Image
X=40
Y=105
W=40
H=258
SolidColor=255,255,255,20
AntiAlias=1
DymamicVariables=1

[Tint1]
Meter=Image
SolidColor=255,0,0,255
SolidColor2=255,0,255,255
GradientAngle=90
X=0r
Y=0r
W=20
H=43
AntiAlias=1
DymamicVariables=1
LeftMouseUpAction=[!WriteKeyValue Variables pointery $MouseY$ "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter (round(255/43*$MouseY$)) "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables trueredsetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "(round(255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables truegreensetter "0" "#@#variables-color.inc"][!Refresh]

[Tint2]
Meter=Image
SolidColor=255,0,255,255
SolidColor2=0,0,255,255
GradientAngle=90
X=0r
Y=0R
W=20
H=43
AntiAlias=1
DymamicVariables=1
LeftMouseUpAction=[!WriteKeyValue Variables pointery (1*43+$MouseY$) "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "(round(255-255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables trueredsetter "(round(255-255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables truegreensetter "0" "#@#variables-color.inc"][!Refresh]

[Tint3]
Meter=Image
SolidColor=0,0,255,255
SolidColor2=0,255,255,255
GradientAngle=90
X=0r
Y=0R
W=20
H=43
AntiAlias=1
DymamicVariables=1
LeftMouseUpAction=[!WriteKeyValue Variables pointery (2*43+$MouseY$) "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "(round(255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables trueredsetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables truegreensetter "(round(255/43*$MouseY$))" "#@#variables-color.inc"][!Refresh]

[Tint4]
Meter=Image
SolidColor=0,255,255,255
SolidColor2=0,255,0,255
GradientAngle=90
X=0r
Y=0R
W=20
H=43
AntiAlias=1
DymamicVariables=1
LeftMouseUpAction=[!WriteKeyValue Variables pointery (3*43+$MouseY$) "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter "(round(255-255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables trueredsetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "(round(255-255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables truegreensetter "255" "#@#variables-color.inc"][!Refresh]

[Tint5]
Meter=Image
SolidColor=0,255,0,255
SolidColor2=255,255,0,255
GradientAngle=90
X=0r
Y=0R
W=20
H=43
AntiAlias=1
DymamicVariables=1
LeftMouseUpAction=[!WriteKeyValue Variables pointery (4*43+$MouseY$) "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "(round(255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables trueredsetter "(round(255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables truegreensetter "255" "#@#variables-color.inc"][!Refresh]

[Tint6]
Meter=Image
SolidColor=255,255,0,255
SolidColor2=255,0,0,255
GradientAngle=90
X=0r
Y=0R
W=20
H=43
AntiAlias=1
DymamicVariables=1
LeftMouseUpAction=[!WriteKeyValue Variables pointery (5*43+$MouseY$) "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "(round(255-255/43*$MouseY$))" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables trueredsetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables truegreensetter "(round(255-255/43*$MouseY$))" "#@#variables-color.inc"][!Refresh]

[TintPointer]
Meter=Image
ImageName=#@#pointer.png
W=20
AntiAlias=1
DymamicVariables=1
X=([TintBG:X]+20)
Y=([TintBG:Y]-10+#pointery#)
ImageTint=#redsetter#,#greensetter#,#bluesetter#
Group=QuickChange


;-------------- Shade
[WindowBG]
Meter=Image
SolidColor=255,255,255,20
X=105
Y=100
W=258
H=259
AntiAlias=1
DymamicVariables=1

[WindowWhite]
Meter=Image
SolidColor=255,255,255,255
X=2r
Y=2r
W=255
H=255
AntiAlias=1
DymamicVariables=1

[WindowColor]
Meter=Image
SolidColor=#tint#,255
SolidColor2=#tint#,0
GradientAngle=180
X=0r
Y=0r
W=255
H=255
AntiAlias=1
DymamicVariables=1

[WindowShade]
Meter=Image
SolidColor=0,0,0,0
SolidColor2=0,0,0,255
GradientAngle=90
X=0r
Y=0r
W=255
H=255
AntiAlias=1
DymamicVariables=1
LeftMouseUpAction=[!SetOption measureTruegreensetter formula "(Round(((255-#greensetter#)*(100-$MouseX:%$)/100+#greensetter#)*(100-$MouseY:%$)/100))"][!UpdateMeasure measureTruegreensetter][!SetOption measureTrueredsetter formula "(Round(((255-#redsetter#)*(100-$MouseX:%$)/100+#redsetter#)*(100-$MouseY:%$)/100))"][!UpdateMeasure measureTrueredsetter][!SetOption measureTruebluesetter formula "(Round(((255-#bluesetter#)*(100-$MouseX:%$)/100+#bluesetter#)*(100-$MouseY:%$)/100))"][!UpdateMeasure measureTruebluesetter][!WriteKeyValue Variables crossx $MouseX$ "#@#variables-color.inc"][!WriteKeyValue Variables crossy $MouseY$ "#@#variables-color.inc"][!MoveMeter "($MouseX$+[WindowShade:X]-5)" "($MouseY$ + [WindowShade:Y]-5)" "ShadeCross"][!SetOption TintPointer ImageTint "(Round(((255-#redsetter#)*(100-$MouseX:%$)/100+#redsetter#)*(100-$MouseY:%$)/100)),(Round(((255-#greensetter#)*(100-$MouseX:%$)/100+#greensetter#)*(100-$MouseY:%$)/100)),(Round(((255-#bluesetter#)*(100-$MouseX:%$)/100+#bluesetter#)*(100-$MouseY:%$)/100))"][!UpdateMeterGroup "QuickChange"][!redraw]


[ShadeCross]
Meter=Image
ImageName=#@#cross.png
AntiAlias=1
DynamicVariables=1
W=10
H=10
X=(#crossx#-5)r
Y=(#crossy#-5)r
Group=QuickChange

;-------------- Result
[ChosenText]
Meter=String
MeterStyle=Text
X=20
Y=([WindowBG:Y]+[WindowBG:H]+10)
Text=Chosen color:

[ChosenBoxBorder]
Meter=Image
SolidColor=255,255,255,20
W=56
H=20
X=10R
Y=0r

[ChosenDefault]
Meter=Image
SolidColor=#defaultColor#
W=26
H=16
DynamicVariables=1
X=2r
Y=2r
Group=QuickChange

[ChosenBox]
Meter=Image
SolidColor=[measureTrueredsetter],[measureTruegreensetter],[measureTruebluesetter]
W=26
H=16
DynamicVariables=1
X=0R
Y=0r
Group=QuickChange

[ChosenRGB]
Meter=String
MeterStyle=Text
X=10R
Y=-2r
Text=RGB: [MeasureTrueredsetter],[MeasureTruegreensetter],[MeasureTruebluesetter]
;Text=RGB: #trueredsetter#,#truegreensetter#,#truebluesetter#
Group=QuickChange

[Apply]
Meter=String
MeterStyle=Text
StringAlign=Center
StringStyle=Bold
H=16
W=150
X=([BG:W]/2)
Y=25R
Text=Apply new color!
LeftMouseUpAction=[!WriteKeyValue Variables last "#changedcolorvariable#" "#@#variables-color.inc"][!WriteKeyValue Variables lastoriginal "#DefaultColor#" "#@#variables-color.inc"][!WriteKeyValue Variables lastnew "[MeasureTrueredsetter],[MeasureTruegreensetter],[MeasureTruebluesetter]" "#@#variables-color.inc"][!WriteKeyValue Variables #changedcolorvariable# "[MeasureTrueredsetter],[MeasureTruegreensetter],[MeasureTruebluesetter]" "#@#variables.inc"][!WriteKeyValue Variables trueredsetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables truegreensetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables pointery "0" "#@#variables-color.inc"][!WriteKeyValue Variables changedcolorvariable "Change me" "#@#variables-color.inc"][!WriteKeyValue Variables DefaultColor "#DefaultColor0#" "#@#variables-color.inc"][!Refresh]

[Line1]
Meter=Image
SolidColor=[MeasureTrueredsetter],[MeasureTruegreensetter],[MeasureTruebluesetter],200
W=[Apply:W]
H=2
X=[Apply:X]
Y=([Apply:Y]-2)
DynamicVariables=1
Group=QuickChange

[Line2]
Meter=Image
SolidColor=[MeasureTrueredsetter],[MeasureTruegreensetter],[MeasureTruebluesetter],200
W=[Apply:W]
H=2
X=[Apply:X]
Y=([Apply:Y]+[Apply:H])
DynamicVariables=1
Group=QuickChange

[Line3]
Meter=Image
SolidColor=[MeasureTrueredsetter],[MeasureTruegreensetter],[MeasureTruebluesetter],200
W=2
H=([Apply:H]+4)
X=([Apply:X]-2)
Y=([Apply:Y]-2)
DynamicVariables=1
Group=QuickChange

[Line4]
Meter=Image
SolidColor=[MeasureTrueredsetter],[MeasureTruegreensetter],[MeasureTruebluesetter],200
W=2
H=([Apply:H]+4)
X=([Apply:X]+[Apply:W])
Y=([Apply:Y]-2)
DynamicVariables=1
Group=QuickChange


[Last]
Meter=String
MeterStyle=Text
X=20
Y=20R
Text="Last color: #last##CRLF#RGB: #lastoriginal#"

[LastBoxBorder]
Meter=Image
SolidColor=255,255,255,20
W=30
H=20
DynamicVariables=1
X=0r
Y=2R

[LastBox]
Meter=Image
SolidColor=#lastoriginal#
W=26
H=16
DynamicVariables=1
X=2r
Y=2r

[changedto]
Meter=String
MeterStyle=Text
X=([Last:X]+[Last:W]+10)
Y=[Last:Y]
Text="changed to#CRLF#RGB: #lastnew#"

[changedtoBorder]
Meter=Image
SolidColor=255,255,255,20
W=30
H=20
DynamicVariables=1
X=0r
Y=2R

[changedtoBox]
Meter=Image
SolidColor=#lastnew#
W=26
H=16
DynamicVariables=1
X=2r
Y=2r

[ChangeBack]
Meter=String
MeterStyle=Text
X=20
Y=5R
Text=Change it back
LeftMouseUpAction=[!WriteKeyValue Variables #last# "#lastoriginal#" "#@#variables.inc"][!WriteKeyValue Variables last "" "#@#variables-color.inc"][!WriteKeyValue Variables lastoriginal "0,0,0" "#@#variables-color.inc"][!WriteKeyValue Variables lastnew "0,0,0" "#@#variables-color.inc"][!Refresh]

[Reset]
Meter=String
MeterStyle=Text
StringAlign=Right
X=([BG:W]-10)
Y=([BG:H]-40)
Text=Reset all
LeftMouseUpAction=[!WriteKeyValue Variables truegreensetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables truebluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables trueredsetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables redsetter "255" "#@#variables-color.inc"][!WriteKeyValue Variables greensetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables bluesetter "0" "#@#variables-color.inc"][!WriteKeyValue Variables crossx "255" "#@#variables-color.inc"][!WriteKeyValue Variables crossy "0" "#@#variables-color.inc"][!WriteKeyValue Variables pointery "0" "#@#variables-color.inc"][!WriteKeyValue Variables changedcolorvariable "Change me" "#@#variables-color.inc"][!WriteKeyValue Variables DefaultColor "#DefaultColor0#" "#@#variables-color.inc"][!Refresh]
