[Variables]
; --------------- Colors
DefaultColor0=255,216,60,255
Color=255,216,60
Color1=#Color#,200
ColorBlack=0,0,0,200
colorborder=255,255,255,20
changedcolorvariable=Change me
DefaultColor=255,216,60,255
last=Btncolor1
lastoriginal=255,216,60,255
lastnew=0,202,255,255

; ---------------- Positions and color mixing
pointery=0
apointery=0
redsetter=255
bluesetter=0
greensetter=0
tint=#redsetter#,#greensetter#,#bluesetter#
trueredsetter=0
truegreensetter=0
truebluesetter=0
alpha=255
crossx=255
crossy=0

hiddena1=1
hiddena2=0
